# Generated by Django 5.0.3 on 2024-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carromodel',
            name='pais',
        ),
        migrations.AlterField(
            model_name='carromodel',
            name='marca',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan')], default='', max_length=50),
        ),
    ]
