# Generated by Django 5.0.3 on 2024-04-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_carromodel_pais_alter_carromodel_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carromodel',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='carromodel',
            name='modelo',
            field=models.CharField(choices=[('Sedane', 'Sedane'), ('Camioneta', 'Camioneta'), ('Híbrido', 'Híbrido')], default='', max_length=50),
        ),
    ]
