# Generated by Django 5.0.3 on 2024-04-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('paisUser', models.CharField(max_length=40)),
                ('ciudad', models.CharField(choices=[('bogota', 'Bogota'), ('medellin', 'Medellin'), ('cali', 'Cali')], default='', max_length=30)),
                ('gen', models.CharField(choices=[('h', 'Hombre'), ('m', 'Mujer')], default='', max_length=5)),
                ('fechNac', models.DateField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
