# Generated by Django 5.0.3 on 2024-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='longitud',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='paisUser',
            field=models.CharField(default='Colombia', max_length=40),
        ),
    ]
