# Generated by Django 5.0.3 on 2024-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usersmodel_latitud_remove_usersmodel_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='barrio',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
