# Generated by Django 5.0.3 on 2024-04-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersmodel_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'Bogota'), ('medellin', 'Medellin'), ('cali', 'Cali')], max_length=30),
        ),
    ]
