# Generated by Django 5.0.3 on 2024-04-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usersmodel_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='barrio',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
