# Generated by Django 5.0.3 on 2024-04-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_remove_carromodel_cantidad_carromodel_modelo'),
        ('users', '0008_alter_usersmodel_barrio_alter_usersmodel_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateField()),
                ('sucursal', models.CharField(max_length=100)),
                ('carro_vendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.carromodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersmodel')),
            ],
        ),
    ]
