# Generated by Django 5.0.3 on 2024-04-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventacarro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventamodel',
            name='sucursal',
            field=models.CharField(choices=[('s1', 'S-001'), ('s2', 'S-002'), ('s3', 'S-003'), ('s4', 'S-004')], max_length=10),
        ),
    ]
