# Generated by Django 5.0.3 on 2024-04-02 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_carromodel_cantidad_carromodel_modelo'),
        ('users', '0008_alter_usersmodel_barrio_alter_usersmodel_ciudad'),
        ('ventacarro', '0002_alter_ventamodel_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventamodel',
            name='carro_vendido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id_Carro', to='inventario.carromodel'),
        ),
        migrations.AlterField(
            model_name='ventamodel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_User', to='users.usersmodel'),
        ),
    ]
